### ISSUE TITLE
make_exe.sh uses deprecated save options

### ISSUE THREAD

**Issue by RdR1024** [Attempto/APE#23]
When executing make_exe.sh on Ubuntu xenial, with swipl version 7.7.16, I get an error message:

ERROR: -g qsave_program('ape.exe', [goal(ape), toplevel(halt), local(25000), global(50000)]).: Domain error: `save_option' expected, found `local'

The error seems to be caused by deprecated use of `local()` and `global()`.  When I replace those two with `stack_limit(75000)`  compilation and execution of ape.exe works.

**Comment by Kaljurand** [comment]
Thanks for pointing this out!

I would propose to remove the stack limit options from the make scripts (because the constants there are anyway unlikely to be suitable for all use cases) and add a few lines to the README saying that different versions of SWI-Prolog have different ways of controlling the stack size. We cannot start using the v7.7 style because this is not a stable version yet.

@tkuhn do you have any suggestions?

**Comment by tkuhn** [comment]
Sounds good to me. I don't remember which practical problems these limits solved back when we added them...
